apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  jwt-secret-raw-value: VGhpc0lzQVJlYWxseUxvbmdBbmRTZWN1cmVLZXlGb3JPdXJBcHAxMjM= # Base64 of 'ThisIsAReallyLongAndSecureKeyForOurApp123' 